language: php

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

php:
  - 7.0

notifications:
  email: itwujunze@gmail.com

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

#Compile
before_script:
    - ./travis/compile.sh

script:
    - exit 0